### ISSUE TITLE
更新到2.0.1版本后，收藏夹里的内容永久丢失了！

### ISSUE THREAD

**Issue by wutaijieing** [vyolit/Kayoko#36]
**Describe the bug:**
updating to version 2.0.1, the content in the favorites is permanently lost!

**Steps to reproduce the behavior:**

**Crash log:**
Upload your log file to pastebin and paste the link here.

**System information:**
- iOS version:15.4.1
- Device:xsmax
- Jailbreak:Dopamine
- Jailbreak Type:rootless

**Comment by vyolit** [comment]
The latest public version is 1.4.2. I don't know where you got a 2.0.1 from. Besides, I don't read chinese.

**Comment by wutaijieing** [comment]
Sorry, I found the wrong place~
