### ISSUE TITLE
Rootful install

### ISSUE THREAD

**Issue by brian6932** [vyolit/Kayoko#38]
**System information:**
- iOS version: 15.8.2
- Jailbreak: palera1n
- Jailbreak Type: Rootful

**Comment by vyolit** [comment]
What are you trying to tell me?

**Comment by brian6932** [comment]
Rootful jailbreaks can't currently install this

**Comment by vyolit** [comment]
The arm64 deb is made for rootless jailbreaks. I don't see why it wouldn't let you install it. Please try a different package manager and or send me a screenshot.

**Comment by brian6932** [comment]
No package manager lets you, they're all frontends for apt. Neither Sileo or Zebra.

**Comment by vyolit** [comment]
Yeah then this has nothing to do with the installation itself.
