### ISSUE TITLE
Seems to open under the current keyboard on ipados-15.8.2

### ISSUE THREAD

**Issue by brian6932** [vyolit/Kayoko#39]
**Describe the bug:**

**Steps to reproduce the behavior:**
The prediction bar doesn't work at all for me. The dictation key does, but shows up under the current keyboard.

**System information:**
- iOS version: 15.8.2
- Device: iPad
- Jailbreak: palera1n
- Jailbreak Type: rootful

**Comment by vyolit** [comment]
Duplicate of #30.
